weston: correct koelsch weston.ini
GENIVI/meta-genivi-dev pull request #31
Opened 2016-08-09 17:40 UTC by slawr

When the maintainers updated to Wayland 1.9.0 and the equivalent IVI-Extension in commit 4f3a052ef7d5d they forgot to update the weston.ini for the Renesas R-Car M2 Koelsch Evaluation board as well. Correct that omission by making the change now.

2016-08-09 17:40 UTC, slawr commented
This issue currently stops the GDP HMI Launcher from starting on the Koelsch board when the GDP sets Kolesch as the MACHINE. Building for Porter and using the Koelsch dtb and kernel it boots ok as we might expect.

I actually question whether this unique Koelsch weston.ini is still required now Weston and the Genivi Compositor components better support multiple screens. I recall it was originally done very early in the history of GDP to resolve an issue because Wayland or QtWayland was not reliably enumerating the screen IDs of the multiple display outputs on the board. I believe testing would show that the turning off LVDS and VGA are no longer required. The state of multi-screen support should be checked with the IVI-Shell/IVI-Extension maintainers and the weston.ini removed if no longer required. In the meantime this PR fixes the issue.

2016-08-16 08:12 UTC, tom--pollard commented
Thanks for spotting this @slawr. If we can get rid of having a unique.ini that would be great, should be a simple test on an existing koelsch rootfs to fiddle with turning the disables off in the .ini I think?

2016-08-16 13:09 UTC, slawr commented
Hi Tom, yes that should be it. I'm 80% certain I did the test back in the day with the previous maintainers but much has changed since then.

2016-08-18 13:54 UTC, tom--pollard commented
Another option is to get rid of the unique .ini and sed/echo the required difference as a machine specific do_install_append step

2016-08-18 13:57 UTC, slawr commented
Yes, good idea if its still needed. Ultimately the test should be done as it is really not a "Kolesch" thing at all but about boards with multiple displays.

2017-01-31 14:09 UTC, zeenix requested changes
I'm not sure about the status of this PR but if it's still valid, please update the commit log as per 
https://at.projects.genivi.org/wiki/display/PROJ/Rules+for+Commit+Messages

2017-01-31 14:39 UTC, slawr commented
@zeenix what do you consider to be a blocker, no sign-off when the PR is generated directly in github?

2017-01-31 14:45 UTC, zeenix requested changes
OK, I guess I should have been more specific. :) 

* "Correct XYZ" is pretty vague, most commits are about correcting things". Let's try to come up with a more specific summary of the change.

* Good work with providing a lot of details in the commit log for a small change but you need to break the lines at 74 characters. The checklist in the commit rules is there so that these small things need not be discussed during reviews. :)

* big nitpick I know but please capitalize the first character of the summary: "weston: Correct".

2017-01-31 14:46 UTC, zeenix commented
@rzr oh and yes, signed-off-by is also missing and if there is a ticket attached to this (which ideally it should be), the reference to that.

2017-01-31 14:54 UTC, slawr commented
@zeenix ok before I address the nitpicks can we address the meat of the discussion thread to see if it is still required? It hasn't moved anywhere since August of last year. It relates to how GDP handles the case when a board has multiple display options. In the very earliest days unless the required display, typically HDMI, was enumerated as the first display the others had to be disabled else it would not be selected. IVI-Extension now has multiple display support.

So the base question is how does GDP select the display to be used?

2017-01-31 17:03 UTC, zeenix commented
@slawr sure thing but if I understood correctly, we just need to test if this is needed for Koelsch?

2017-01-31 17:56 UTC, rzr commented
@zeenix you said "@rzr oh and yes, signed-off-by is also missing ..."   or it's for the other PR from me ?

2017-02-01 14:16 UTC, zeenix commented
@rzr no, the commit message in question, lacks 'signed-off-by' line AFAICT

2017-02-01 17:15 UTC, rzr commented
OK, it's @slawr change not mine :)

2017-02-01 18:02 UTC, zeenix commented
@rzr ah true, sorry. @slawr it's on you then. :)

2017-02-21 17:42 UTC, slawr commented
This PR has been open since August of last year. Let me try to summarise the situation so we can progress this.

1. As described in the first comment this PR addresses an issue caused by commit 4f3a05 which modified the Weston.ini behaviour but failed to also update the ini for the R-Car M2 Koelsch board. The effect is that the GDP HMI will not start when built for the Koelsch. This PR corrects that issue.

2. I have updated the PR to add a signed-off.

3. I wondered whether the ini was still really required. As explained in the comments it was created in the early days of GDP to ensure GDP selected the HDMI output on a board with multiple outputs. However based on my experience with Gen 3 I suspect it still is. There is a question around how GDP makes the display selection when multiple displays are available? However as the comment history shows it just complicates this PR.

I propose point 3 be dealt with separately as it probably should and this PR concentrate on 1.

2017-02-22 11:25 UTC, zeenix commented
@slawr thanks. I'd merge this already but seems all builds against this PR are failing. Not sure how this change could possibly break sota-client though.

2017-03-02 14:06 UTC, slawr commented
@zeenix, @gunnarx: Looking at the RiP and Porter builds it is failing due to an access issue at build time unrelated to this PR:
```
12:08:07.749 | error: failed to load source for a dependency on `rust-crypto`
12:08:07.749 | 
12:08:07.749 | Caused by:
12:08:07.749 |   Unable to update registry https://github.com/rust-lang/crates.io-index
12:08:07.749 | 
12:08:07.749 | Caused by:
12:08:07.749 |   failed to update replaced source `registry https://github.com/rust-lang/crates.io-index`
```

2017-03-02 15:51 UTC, zeenix commented
@slawr yeah but I see now that builds are old by now. I restarted the builds for this PR, lets see..

2017-03-02 16:07 UTC, zeenix commented
@slawr ah i think you gotta rebase for build system to get new good changes in :) but it's ok, I'll merge already since it's very unlikely to break anything.

2017-03-02 16:07 UTC, merged

2017-03-02 17:17 UTC, slawr commented
Thanks. Nice to get this merged after so long. Who is supposed to do the closing of the PR itself?

2017-03-03 17:45 UTC, zeenix commented
@slawr PR is closed with the merge. :)

2017-03-23 22:33 UTC, gunnarx commented
> @slawr PR is closed with the merge. :)

... but corresponding JIRA issues are not.  Me and Zeeshan moved them to In Review status today, so what remains is that someone tests and confirms the right behavior.