NodeStateTest and Lifecycle targets
GENIVI/meta-genivi-dev pull request #61
Opened 2017-02-15 14:32 UTC by DunderRoffe

2017-02-15 15:57 UTC, chbae requested changes

2017-02-15 15:57 UTC, chbae commented on meta-genivi-dev/recipes-core/systemd/systemd_%.bbappend
> +    install -m 0644 ${WORKDIR}/lazy.target      ${D}/lib/systemd/system/lazy.target
${D}/lib/systemd/system -> ${D}${systemd_system_unitdir}

2017-02-15 15:57 UTC, chbae commented on meta-genivi-dev/recipes-core/systemd/systemd_%.bbappend
> +    install -m 0644 ${WORKDIR}/unfocused.target ${D}/lib/systemd/system/unfocused.target
${D}/lib/systemd/system -> ${D}${systemd_system_unitdir}

2017-02-15 15:57 UTC, chbae commented on meta-genivi-dev/recipes-core/systemd/systemd_%.bbappend
> +    install -m 0644 ${WORKDIR}/focused.target   ${D}/lib/systemd/system/focused.target
${D}/lib/systemd/system -> ${D}${systemd_system_unitdir}

2017-02-15 15:59 UTC, chbae commented
NodeStateManager: install NodeStateTest -> Why do you install test binary into target?

2017-02-16 10:15 UTC, zeenix requested changes
As usual, @chbae quickly takes care of review of patch itself so I can focus on commit log. :) Actually this is a pretty good one and I don't need to complain much about syntax:

* There is no such thing as "lifecycle" technically speaking so we really shouldn't refer to it as such. Especially the last sentence makes it sound like "GDP-lifecycle" is the name of a software that we'll be integrating later, which is not at all the case here.

* You're missing jira ticket reference.

* Please don't break lines for new sentences. This is supposed to be normal English text so only good reason to break to new line are
  * starting a new paragraph (in which case you need an empty line in between the paragraphs)
  * You hit 74 chars limit.

2017-02-16 10:17 UTC, zeenix requested changes
Some rationale in details of why this change is needed, would be nice. Also missing the jira reference.

2017-02-16 11:32 UTC, DunderRoffe commented
@chbae The test binary is included as a tool to demonstrate that NSM works on the target.

2017-02-16 11:34 UTC, DunderRoffe commented
Sure @zeenix this pull-request was a bit stressed as I wanted to get it up before the team meeting

2017-02-16 12:09 UTC, zeenix approved these changes

2017-02-16 12:09 UTC, zeenix commented
@chbae looks good to me now, once you're satisfied please approach the changes and merge.

2017-02-16 13:14 UTC, zeenix requested changes
On second thought, why bbappend here and not do this in the recipe (in meta-ivi)? We already have a lot of bbappend and we want to reduce them.

2017-02-17 07:34 UTC, DunderRoffe commented
Because that would affect any other project using meta-ivi. I am not sure that every other project wants to build the test binary

2017-02-17 10:07 UTC, zeenix commented
@DunderRoffe good point. :)

2017-02-17 10:07 UTC, zeenix approved these changes

2017-02-20 19:25 UTC, gunnarx commented
Sorry to come in late with this review but I have preferences and pointers to make:

Licenses:

- Generally apply MPLv2 (GENIVI default license) unless you have a good reason. Even when there is a good reason to apply (L)GPL, the GENIVI license policy only allows LGPL v2.1 for straight-up libraries.

Since you didn't avoid LGPL naturally here, I assume an explanation might help:  I feel the license is confusing and possibly even legally ambiguous when applied to non-library code (despite that it mentions "other program" in the introduction, it is very clear the rest of it has been designed with libraries in mind).
The GENIVI license review team used similar reasoning when decising on the policy.

Here, I'd personally prefer a permissive license or CC0 for the really uninteresting metadata (which I would consider systemd unitfiles to be).  I'd recommend that we decide and document a guideline for all "system configuration" type data in GDP and make sure we are at least consistent.

2017-02-20 19:27 UTC, gunnarx commented
I also react to the bbappend, but the one for systemd.  The files are part of defining the GDP system, not really part of building systemd itself.  I wonder if there is a more natural place to put them.

2017-02-23 15:42 UTC, zeenix commented
@chbae are you concerns satisfied now? If so, please do approve the changes.

@gunnarx how about yours? Please set "request changes" in your reviews if that's the case so it's easy to track the status of PR. Thanks.

2017-03-01 17:08 UTC, chbae approved these changes

2017-03-01 17:10 UTC, chbae commented
Sorry for late review.

2017-03-02 10:45 UTC, merged