Aktualizr
GENIVI/meta-genivi-dev pull request #64
Opened 2017-02-17 17:24 UTC by leon-anavi

Hi,

The following changes are provided:
* Align with the latest changes from the master branch
* Update Aktualizr to a newer version with cmake file that allows skipping the build of the tests in the Yocto/OE recipe
* Remove gmock Yocto/OE as it is no longer needed by Aktualizr
* Add systemd service for Aktualizr

Best regards,
Leon

2017-02-17 21:13 UTC, gunnarx commented
1. Why is "navit: Remove Navit & all it's dependents" commit part of the PR?  
(Whatever the reason, it has been merged now anyway so you might have to rebase, @leon-anavi)

2. Secondly, the PR builds seem to fail because there is no branch named fix/boost-yocto in the ATS aktualizr repository, and the SRCREV a6136f091 is also missing as far as I can see.
Click on any "details" link above to go to go.genivi.org

2017-02-19 17:08 UTC, chbae requested changes
Could you rebase on current master? and why don't you remove merge commit?

2017-02-19 17:08 UTC, chbae commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
>  RDEPENDS_aktualizr = "dbus-lib"
I thought that this is not required.

2017-02-19 17:08 UTC, chbae commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +  install -d ${D}${systemd_unitdir}/system
1. ${systemd_unitdir}/system -> ${systemd_system_unitdir}
2. I recommend that you use 4 spaces

2017-02-19 17:08 UTC, chbae commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +  install -m 0644 ${WORKDIR}/aktualizr.service ${D}${systemd_unitdir}/system
${systemd_unitdir}/system -> ${systemd_system_unitdir}

2017-02-19 17:08 UTC, chbae commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +              ${systemd_unitdir}/system/aktualizr.service \
${systemd_unitdir}/system -> ${systemd_system_unitdir}

2017-02-19 17:08 UTC, chbae commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
>                ${libdir}/libjwt.so.0.3.0 \
those 3 lines are really required?

2017-02-19 22:10 UTC, leon-anavi commented
Hi @gunnarx, @chbae,

Thank you for the provided feedback. I am on my way to ELC therefore I will not be able to address these issues immediately. The "navit: Remove Navit & all it's dependents" commit is part of the PR because I have merged the latest changes from master in this branch. As @chbae suggested I will rebase again and remove the merge commit. Yesterday I emailed ATS Advanced Telematic Systems asking about branch fix/boost-yocto. I will fix and provide an update of the recipes as soon as I return from ELC.

Best regards,
Leon

2017-02-20 06:50 UTC, chbae commented
@leon-anavi Cool. enjoy your trip :)

2017-03-07 12:51 UTC, zeenix commented
@leon-anavi I hope you had a great trip and talk! I just wanted to remind you about this PR.

2017-03-07 16:32 UTC, leon-anavi commented
Hi,

ATS Advanced Telematic Systems informed me that Aktualizr is ready for upstreaming in meta-genivi-dev master branch therefore I will close this GitHub pull request, address the issues pointed out by @gunnarx, @chbae, @zeenix, get rid of some redundant patches (like the one for gmock) and rebase just the needed patches on top of master.

Best regards,
Leon

2017-03-07 16:32 UTC, closed without merging

2017-03-08 09:40 UTC, zeenix commented
That's great to hear @leon-anavi ! I'd highly recommend reusing this PR (if possible) but no biggie if you don't.

2017-03-08 11:00 UTC, cajun-rat commented
@zeenix Is there a reason why we shouldn't be merging to master--what would be the benefit of merging from our branch, then to a branch in GENIVI, then to GENIVI master?

2017-03-08 11:30 UTC, zeenix commented
@cajun-rat Actually we prefer merging to master always. Please read the thread here for reasons on why it was done this way: https://github.com/GENIVI/meta-genivi-dev/pull/58

2017-03-08 11:34 UTC, zeenix commented
@cajun-rat @leon-anavi Although now that I think more about it, I don't see the point of having a branch for a contributor in the mainline repository if the contributor in question doesn't have write-access to the repo. Since one can always create a clone with 1 click and then also very easily create a PR from there, I think we shouldn't do this in future.

2017-03-08 13:47 UTC, leon-anavi commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +  install -m 0644 ${WORKDIR}/aktualizr.service ${D}${systemd_unitdir}/system
OK, thank you. I have fixed it.

2017-03-08 13:47 UTC, leon-anavi commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +  install -d ${D}${systemd_unitdir}/system
OK, thank you.

2017-03-08 13:54 UTC, leon-anavi commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
> +              ${systemd_unitdir}/system/aktualizr.service \
OK, thank you.

2017-03-08 14:01 UTC, leon-anavi commented on meta-genivi-dev/recipes-sota/aktualizr/aktualizr_git.bb
>  RDEPENDS_aktualizr = "dbus-lib"
Yes, according to the [mega manual ](http://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#ref-classes-systemd) there is no need of SYSTEMD_PACKAGES if the service is in the main package. The name of the service file should be in SYSTEMD_SERVICE.

2017-03-14 09:39 UTC, cajun-rat commented
@zeenix Yes, that makes sence