gdp-new-hmi: Change binary name to gdp-hmi
GENIVI/meta-genivi-dev pull request #65
Opened 2017-02-26 16:53 UTC by chbae

genivi-11-hmi that is previous binary name is only for GDP-11 and need
to change general naming. So I change the binary name to gdp-hmi.

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

2017-02-27 12:49 UTC, zeenix requested changes

2017-02-27 12:49 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> -
Please put each logical change in it's own patch/commit with it's own commit log, no matter how small. This patch should only and only contain changes need to rename the binary (source files/recipe renames can & should also be part of it but then you need to remove 'binary' from commit log).

2017-03-07 12:50 UTC, zeenix commented
@chbae will you be working on this?

2017-03-07 14:36 UTC, chbae commented
I'll apply your review tonight. :)

2017-03-08 14:09 UTC, chbae commented
@zeenix 
DONE. Please review this.

2017-03-08 15:08 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +    install -m 0444 ${WORKDIR}/git/manifests/* ${D}${datadir}/applications/
Sorry to be very pedantic about this but here you're also changing the indentation, which is unrelated to the patch and hence needs to be done separately. I suggest breaking it out into a separate patch that goes before this one.

2017-03-13 00:56 UTC, chbae commented
@zeenix 
Now I only change the naming.

2017-03-13 11:09 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
Also changing the revision still. :)

2017-03-13 11:09 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +    /opt/gdp-hmi/bin/gdp-hmi \
So is this the only change that was needed for rename?

2017-03-13 14:16 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
This change is for renaming.

2017-03-13 14:16 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +    /opt/gdp-hmi/bin/gdp-hmi \
no. need to change SRCREV.

2017-03-13 14:23 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
Ah I see now that you changed the name in HMI itself. In this case, the update of HMI here is the real change and renaming is just a side-effect, from the point of view of meta-genivi-dev. Hence I'd like the commit log to be changed.

2017-03-13 14:49 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
@zeenix I thought that current commit message is enough. Please write it what you want. Thanks.

2017-03-14 09:32 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
@chbae It's not that it's not enough, it's that it's wrong. You're summarizing a side-effect, not the change. I can't be writing commit messages for everyone. :) Please try yourself first and if you fail, I'll help. Deal? :)

2017-03-14 14:43 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
@zeenix 

My commit is not about side effect and 79a4f69e7588a6efc4b4c95abec7794216588087 is also for changing naming. So 79a4f69e7588a6efc4b4c95abec7794216588087 in component repo and my recipe change are for naming changing.

I thought that you don't understand this change.

2017-03-14 16:54 UTC, zeenix commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
As I tried to explain above, from the **point of view of m-g-d** (which is what you are changing here), change of name is a side-effect. It's very similar to submodule updates in g-d-p repo and you can see from the log (and our new script) how we don't mention the actual changes in the shortlog but rather in the description.

Anyway, I'll modify the commit log for you.

2017-03-14 23:57 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/gdp-new-hmi.bb
> +SRCREV = "79a4f69e7588a6efc4b4c95abec7794216588087"
@zeenix Ok. thanks. However, I think that recipe and repo change is one package.
That's different from each reviewers. If you give your idea, I respect you.

2017-03-15 11:46 UTC, merged