Add sdl packagegroup to genivi dev platform image
GENIVI/meta-genivi-dev pull request #67
Opened 2017-03-05 09:18 UTC by phongt

#Add sdl-core in genivi dev platform.

Signed-off-by: Phong Tran <tranmanphong@gmail.com>

2017-03-05 09:19 UTC, phongt commented
This related to https://github.com/GENIVI/genivi-dev-platform/pull/66

2017-03-05 18:05 UTC, chbae commented
@phongt  Could you share how to test this feature in GDP?

2017-03-06 10:16 UTC, zeenix requested changes
Thanks for submitting these patches! I'll do a proper review later but one of the first thing I noticed is that you're missing the Jira ticket tag in your commit messages. The ticket is GDP-177.

2017-03-06 14:06 UTC, phongt commented
@chbae Please get https://github.com/GENIVI/genivi-dev-platform/pull/66 and this PR.
$ bitbake genivi-dev-platform
The SDL core will be build and install to the image.
@zeenix  Please review and give your feedback. I will update both commit message and upcoming comments.

2017-03-06 15:17 UTC, zeenix commented
@phongt I believe @chbae was asking for a way to actually test these new components, not just build them. :)

2017-03-06 15:24 UTC, zeenix requested changes
Apart from missing jira ticket reference there is only 1 minor issue in the patch itself and some nitpicks about commit log:

* Would be nice to have a bit more details in the commit log. 
* Either write "Genivi Development Platform"  or "genivi-dev-platform".
* "add to" not "add in"

2017-03-06 15:24 UTC, zeenix commented on meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-sdl.bb
> +# Avoid hardcoding the full layer path into the checksums
Is this a FIXME comment? If so, please append "FIXME: " so it's clear that it's what you should be doing rather than what you are already doing.

2017-03-06 15:44 UTC, gunnarx commented
Me and @zeenix agree that the build check fails as expected because of dependency on [genivi-dev-platform/pull/66]( https://github.com/genivi/genivi-dev-platform/pull/66)

2017-03-06 15:47 UTC, zeenix commented
> Me and @zeenix agree that the build check fails as expected because of dependency on genivi-dev-platform/pull/66

Indeed but what we might not agree on is that we'll first merge g-d-p change and then this PR should build. :)

2017-03-07 15:28 UTC, chbae commented
@phongt  
I would like to know real test in environment. How can I test? Which devices do you test like raspberrypi, qemux86-64 or others?

2017-03-07 22:58 UTC, phongt commented on meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-sdl.bb
> +# Avoid hardcoding the full layer path into the checksums
This packagegroup bb file is inherited from other packagegroup in meta-genivi-dev/recipes-dev-platform/packagegroups/. This is not FIXME. It 's a comment that is introduced in [ccad2e3](https://github.com/GENIVI/meta-ivi/commit/ccad2e3) .

2017-03-08 09:35 UTC, zeenix commented on meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-sdl.bb
> +# Avoid hardcoding the full layer path into the checksums
OK

2017-03-09 01:16 UTC, phongt commented
> Apart from missing jira ticket reference there is only 1 minor issue in the patch itself and some nitpicks about commit log:
> - Would be nice to have a bit more details in the commit log.
> - Either write "Genivi Development Platform" or "genivi-dev-platform".
> - "add to" not "add in"

@zeenix I updated the commit log as your review comments.
>I would like to know real test in environment. How can I test? Which devices do you test like raspberrypi, qemux86-64 or others?

@chbae  Currently just simple testing by checking sdl_core via 'systemctl  status smartdevicelink'.  And some logs file can found in /var/log/smartdevicelink/. This is tested in QEMU x86_64 environment.

2017-03-09 13:42 UTC, zeenix commented
> @chbae Currently just simple testing by checking sdl_core via 'systemctl status smartdevicelink'. And some logs file can found in /var/log/smartdevicelink/. This is tested in QEMU x86_64 environment.

Hmm.. This PR made us discuss in the team yesterday if we should always require a UI demo for all new features as "merge policy". Do you think that could be arranged?

We're hoping to have automated UI tests in place at some point soon so a UI for each new feature would mean easy addition of automated tests for all major features.

2017-03-09 13:48 UTC, zeenix reviewed
Thanks for fixing the commit message. Some more stuff but I can fix that for you if you like (though please keep in mind that this favour is only for new contributors) once we have sorted testing/UI question: 

* Module prefix missing from shortlog.
* "to genivi-dev-platform image" part in shortlog is redundant and only makes shortlog longer than it should be (50 chars) once you add the prefix.
* Empty line after shortlog please. Besides with current shortlog, the first line is redundant.
* "Jira ticket" line is redundant IMO but if you want to keep it, add a ":" at the end please.

2017-03-10 11:56 UTC, tom--pollard commented
> Hmm.. This PR made us discuss in the team yesterday if we should always require a UI demo for all new features as "merge policy". Do you think that could be arranged?

I'm not sure this appropriate for all applications, but it could be argued that non-frontended applications should be merged into baseline

2017-03-10 12:17 UTC, zeenix commented
@tom--pollard sure, but would make sense for frameworks.

2017-03-11 03:04 UTC, phongt commented
@zeenix Updated commit log. Thank you for your checking.

> Hmm.. This PR made us discuss in the team yesterday if we should always require a UI demo for all new features as "merge policy". Do you think that could be arranged?
I think, If there is a UI demo for SDL in GDP, It will be more impressive. I will consider about it.

2017-03-12 19:45 UTC, gunnarx commented
Build checks: Unfortunately I introduced a small bug in **all** m-g-d PR check pipelines when I added dragonboard to the checks.  But that is now fixed and these are failing for the "right reason" now, i.e. that sdl-core is not yet available.  As @phongt says that's [genivi-dev-platform/pull/66](https://github.com/genivi/genivi-dev-platform/pull/66)

2017-03-12 19:47 UTC, gunnarx commented
@phongt you might want to see which example UI might be provided in the SDL code base these days (there used to be one if I remember correctly)

2017-03-13 11:04 UTC, zeenix approved these changes

2017-03-22 11:45 UTC, gunnarx commented
For the record it would have been better in this thread, but I mentioned some info on the default UI in genivi/genivi-dev-platform/pull/66

2017-06-01 23:05 UTC, gunnarx commented
Rebased this on chromium branch (will use chromium for the HMI so might as well) and pushed to update the PR.

2017-06-02 13:38 UTC, gunnarx commented
Turns out commit 1b9a7e0 is bad and shouldn't have ended up on this branch.  Another rebase attempt and push.

2017-06-13 09:27 UTC, gunnarx commented
@phongt Since we're tracking this on a feature branch instead, I think the PR can be closed and communication can happen on the [relevant tickets|https://at.projects.genivi.org/jira/browse/GDP-177] instead.

Also, the [meta-genivi-dev merge into g-d-p](http://lists.genivi.org/pipermail/genivi-projects/2017-June/005539.html) is happening now so I'm trying to remove as many m-g-d PRs as possible since they will not be appropriate after this merge.

2017-06-13 10:42 UTC, phongt commented
@gunnarx   Okay. I closed

2017-06-13 10:42 UTC, closed without merging