Add CDL concept demo codes
GENIVI/meta-genivi-dev pull request #79
Opened 2017-04-10 13:59 UTC by summeromance

This PR includes the initial integration for CDL concept demo codes into GDP.
The CDL Concept Demo was not yet integrated with the GDP HMI Launcher because it was designed to run different binaries on three GDP devices respectively.
Currently, each GDP device must be tested by running it through a pre-provided script included in the image.
This code will be able to integrate with the HMI Launcher in the future.

[GDP-500] Integrate Car Data Logger (CDL) into GDP

2017-04-10 14:34 UTC, gunnarx commented
Great.  The build checks suggest there might be some CommonAPI version mismatch here so let's investigate.

2017-04-10 15:01 UTC, gunnarx commented
@summeromance Could you post the commit hash values that you have used for other layers when you built it successfully?  (Most likely we are using different versions of meta-ivi)

2017-04-10 15:20 UTC, summeromance commented
I tested this with morty branch of genivi-dev-platform.
Hash values are
  - genivi-dev-platform : 79002aeb7da0685fce88e2770d0512e5ac6fca34
       - meta-ivi : 860f0ce4540412c25d74dd9f53859b24fcb56300
       - meta-genivi-dev : b5b76411194b2b4a73f9bff2a4ce6b7c41b24904

2017-04-10 15:58 UTC, gunnarx commented
Ah ok, that explains it.  The build checks executed here are using master, which is not yet switched over to Morty.  So that definitely explains the mismatch in CommonAPI version.  Which hardware(s) did you build for?

2017-04-10 23:05 UTC, summeromance commented
I tested on Raspberry Pi3.
Should I create PR to morty branch?

2017-04-10 23:17 UTC, gunnarx commented
Not requesting you to change the PR right now because Morty branch is temporary and there are no build checks for PRs to that branch anyway so we will not learn anything new.  No I think it's more likely we switch master over to Morty and then rebase this on top of that.  I'll discuss with @zeenix.

2017-04-11 14:41 UTC, chbae requested changes
@gunnarx, @zeenix 
We need to discuss about packagegroup because purpose of packagegroup is for component bundle. However, CDL is just a component and I thought that packagegroup is not required for CDL.

Why don't we create general packagegroup (ex, packagegroup-gdp-extended) for like CDL components?

Please give your opinion.

2017-04-11 14:41 UTC, chbae commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +# Copyright (C) 2015-2016 GENIVI Alliance
# Copyright (C) 2017 GENIVI Alliance

2017-04-11 14:41 UTC, chbae commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +
SUMMARY = "CDL Concept Demo"

2017-04-11 14:41 UTC, chbae commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +SUMMARY = "CDL Concept Demo"
Please move to below "copyright"

2017-04-11 14:41 UTC, chbae commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +INSANE_SKIP_${PN} = "dev-so"
I'm not sure that this line is really required?

2017-04-11 15:05 UTC, gunnarx commented
>  We need to discuss about packagegroup because purpose of packagegroup is for component bundle. 
> However, CDL is just a component and I thought that packagegroup is not required for CDL.
@chbae  I agree with your assessment.  I have too many other more important things to consider now however.  Maybe the rest of you can just agree on something simple?

2017-04-11 16:35 UTC, gunnarx commented
FYI: On a separate machine I am building this on top of GDP Morty branch as an alternative build check.  I imagine I will have the result tomorrow.

2017-04-12 00:41 UTC, chbae commented
@gunnarx Thanks
@zeenix Please give me your opinion. I would like to use "packagegroup-gdp-extended".

2017-04-12 02:27 UTC, summeromance commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +INSANE_SKIP_${PN} = "dev-so"
There is an error during do_package_qa. Error is "non dev package contains symlink."
Should I install files manually?

2017-04-12 11:15 UTC, chbae commented
@summeromance 
Your PR is not merged and you don't need to create new commit to apply my comment.
Please use "amend" commit in your existed commit.

2017-04-12 12:39 UTC, chbae commented on meta-genivi-dev/recipes-cdl/cdl-concept-demo/cdl-concept-demo.bb
> +INSANE_SKIP_${PN} = "dev-so"
@summeromance 
I agree with you. you don't need to change it.

2017-04-12 12:51 UTC, summeromance commented
It seems to be a mistake because I am not familiar with the GitHub process and it is first time amend to the commit that already pushed to remote. Two commits that added for packagegroups have disappeared.
There is a discussion about packagegroup, so is it better to make a new commit if it is determined, or should I re-create the commit as it is?

2017-04-13 11:00 UTC, zeenix commented
I'm a bit confused, the latest commit is only adding the recipe but not adding it to the image (which would explain the builds magically starting to succeed). Regarding package-group, I don't have a strong opinion but looking at the existing package-groups, it seems that we would like a -cdl packagegroup, similar to -fsa, -hmi, -browser etc.

2017-04-14 01:48 UTC, summeromance commented
> I'm a bit confused, the latest commit is only adding the recipe but not adding it to the image (which would explain the builds magically starting to succeed). 

@zeenix As I commented, that is my fault.

2017-04-14 02:42 UTC, summeromance commented
> @zeenix Please give me your opinion. I would like to use "packagegroup-gdp-extended".

> Regarding package-group, I don't have a strong opinion but looking at the existing package-groups, it seems that we would like a -cdl packagegroup, similar to -fsa, -hmi, -browser etc.

@zeenix @chbae zeenix suggested creating a cdl package group, and chbae suggested that create an extended package group and include CDL there. It seems difficult to determine which package group the CDL concept demo should be included in.

2017-04-16 20:20 UTC, zeenix commented
@summeromance people can't always have the same opinions. I explained that i don't have strong opinions but presented the reasoning behind my opinion. Maybe you can give it a thought and provide your conclusion/assessment?

2017-04-16 23:56 UTC, chbae commented
@summeromance 
If you have any plan to add more components in packagegroup-gdp-cdl, It's better to use packagegroup-gdp-cdl. Or If not, please use common packagegroup (packagegroup-gdp-extended). That's one of opinion as @zeenix said.

2017-04-17 02:34 UTC, summeromance commented
@zeenix @chbae Thank you for the suggestions.

I mean it's hard to decide which package group to include in the CDL, because the CDL is not yet part of a specific expert group and is being run as a subproject of KREG. This is also why I was worried about where to put the UML when I registered the CDL as a Placeholder Component.

So I agree with chbae, but the code I'm registering now is a kind of proof of concept as Placeholder Component of the CDL, and now I'm implementing the PoC of the abstract component, which I will also promote to integrate into the GDP later, so I agree with zeenix also.

2017-04-17 11:06 UTC, summeromance commented
@chbae @zeenix I created the commit to add the package group for the CDL, which is the same as the commit I originally made. Once again thank you for your suggestions.

2017-04-18 16:08 UTC, zeenix commented
@summeromance Thanks. Seems the build is now failing:

```
12:05:36.091 | ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.cpp:22:200:   required from here
12:05:36.091 | ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.hpp:167:18: error: type 'CommonAPI::DBus::DBusStubAdapter' is not a direct or virtual base of 'v1::com::ivis::CDL::ClientAPILocalDBusStubAdapter<v1::com::ivis::CDL::ClientAPILocalStub>'
12:05:36.091 |              _stub) {
12:05:36.091 |                   ^
12:05:36.091 | In file included from ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.hpp:23:0,
12:05:36.091 |                  from ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.cpp:11:
12:05:36.091 | /var/lib/go-agent/pipelines/GDP-Yocto-Dragonboard-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/dragonboard-410c/usr/include/CommonAPI-3.1/CommonAPI/DBus/DBusStubAdapterHelper.hpp: In instantiation of 'static bool CommonAPI::DBus::DBusStubSignalHelper<In_<CommonAPI::DBus::DBusInputStream, CommonAPI::DBus::DBusOutputStream, InArgs_ ...> >::sendSignal(const DBusStub_&, const char*, const char*, const InArgs_& ...) [with DBusStub_ = v1::com::ivis::CDL::ClientAPILocalDBusStubAdapterInternal<v1::com::ivis::CDL::ClientAPILocalStub>; In_ = CommonAPI::SerializableArguments; InArgs_ = {CommonAPI::Deployable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CommonAPI::DBus::StringDeployment>, CommonAPI::Deployable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CommonAPI::DBus::StringDeployment>, CommonAPI::Deployable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CommonAPI::DBus::StringDeployment>, CommonAPI::Deployable<CommonAPI::Variant<bool, short int, short unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, CommonAPI::DBus::VariantDeployment<CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment, CommonAPI::DBus::StringDeployment> >}]':
12:05:36.091 | ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.hpp:139:19:   required from 'void v1::com::ivis::CDL::ClientAPILocalDBusStubAdapterInternal<_Stub, _Stubs>::fireNotifyDataEvent(const string&, const string&, const string&, const CDLData&) [with _Stub = v1::com::ivis::CDL::ClientAPILocalStub; _Stubs = {}; std::__cxx11::string = std::__cxx11::basic_string<char>; v1::com::ivis::CDL::ClientAPILocalTypes::CDLData = CommonAPI::Variant<bool, short int, short unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >]'
12:05:36.091 | ../../../git/project/interface/src-gen/v1/com/ivis/CDL/ClientAPILocalDBusStubAdapter.cpp:37:1:   required from here
12:05:36.091 | /var/lib/go-agent/pipelines/GDP-Yocto-Dragonboard-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/dragonboard-410c/usr/include/CommonAPI-3.1/CommonAPI/DBus/DBusStubAdapterHelper.hpp:259:26: error: 'const class v1::com::ivis::CDL::ClientAPILocalDBusStubAdapterInternal<v1::com::ivis::CDL::ClientAPILocalStub>' has no member named 'getDBusAddress'
12:05:36.091 |          return(sendSignal(_stub.getDBusAddress().getObjectPath().c_str(),
12:05:36.091 |                           ^
12:05:36.091 | /var/lib/go-agent/pipelines/GDP-Yocto-Dragonboard-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/dragonboard-410c/usr/include/CommonAPI-3.1/CommonAPI/DBus/DBusStubAdapterHelper.hpp:259:26: error: 'const class v1::com::ivis::CDL::ClientAPILocalDBusStubAdapterInternal<v1::com::ivis::CDL::ClientAPILocalStub>' has no member named 'getDBusAddress'
12:05:36.092 | /var/lib/go-agent/pipelines/GDP-Yocto-Dragonboard-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/dragonboard-410c/usr/include/CommonAPI-3.1/CommonAPI/DBus/DBusStubAdapterHelper.hpp:259:26: error: 'const class v1::com::ivis::CDL::ClientAPILocalDBusStubAdapterInternal<v1::com::ivis::CDL::ClientAPILocalStub>' has no member named 'getDBusConnection'
12:05:36.092 | Makefile:431: recipe for target 'release/arm/.obj/ClientAPILocalDBusStubAdapter.o' failed
12:05:36.092 | make[1]: *** [release/arm/.obj/ClientAPILocalDBusStubAdapter.o] Error 1
12:05:36.092 | ../../../git/project/interface/src-gen/v1/com/ivis/ModeManager/ModeManagerDBusProxy.cpp: In function 'void v1::com::ivis::ModeManager::registerModeManagerDBusProxy()':
12:05:36.092 | ../../../git/project/interface/src-gen/v1/com/ivis/ModeManager/ModeManagerDBusProxy.cpp:30:38: error: 'class CommonAPI::DBus::Factory' has no member named 'registerInterface'
12:05:36.092 |      CommonAPI::DBus::Factory::get()->registerInterface(initializeModeManagerDBusProxy);
12:05:36.092 |                                       ^
12:05:36.092 | Makefile:448: recipe for target 'release/arm/.obj/ModeManagerDBusProxy.o' failed
12:05:36.092 | make[1]: *** [release/arm/.obj/ModeManagerDBusProxy.o] Error 1
12:05:36.092 | In file included from ../../../git/project/mode-manager/src/ModeManagerService.h:27:0,
12:05:36.092 |                  from ../../../git/project/mode-manager/src/ModeManagerService.cpp:23:
12:05:36.092 | ../../../git/project/interface/src-gen/v1/com/ivis/ModeManager/ModeManagerStubDefault.hpp:45:5: error: expected initializer before ':' token
12:05:36.092 |      : public virtual ModeManagerStub {
12:05:36.092 |      ^
12:05:36.092 | In file included from ../../../git/project/mode-manager/src/ModeManagerService.cpp:23:0:
12:05:36.092 | ../../../git/project/mode-manager/src/ModeManagerService.h:34:20: error: expected '}' before end of line
12:05:36.092 | ../../../git/project/mode-manager/src/ModeManagerService.h:34:20: error: expected '}' before end of line
12:05:36.092 | ../../../git/project/mode-manager/src/ModeManagerService.h:34:20: error: expected '}' before end of line
12:05:36.092 | ../../../git/project/mode-manager/src/ModeManagerService.h:34:20: error: expected '}' before end of line
12:05:36.092 | ../../../git/project/mode-manager/src/ModeManagerService.h:34:20: error: expected declaration before end of line
12:05:36.092 | Makefile:413: recipe for target 'release/arm/.obj/ModeManagerService.o' failed
12:05:36.092 | make[1]: *** [release/arm/.obj/ModeManagerService.o] Error 1
12:05:36.093 | make[1]: Leaving directory '/var/lib/go-agent/pipelines/GDP-Yocto-Dragonboard-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/aarch64-poky-linux/cdl-concept-demo/1.0-r0/build/project/cdl-client-api'
12:05:36.093 | Makefile:79: recipe for target 'sub-project-cdl-client-api-make_first' failed
12:05:36.093 | make: *** [sub-project-cdl-client-api-make_first] Error 2
12:05:36.093 | ../../../git/project/interface/src-gen/v1/com/ivis/ModeManager/ModeManagerDBusProxy.cpp: In function 'void v1::com::ivis::ModeManager::registerModeManagerDBusProxy()':
12:05:36.093 | ../../../git/project/interface/src-gen/v1/com/ivis/ModeManager/ModeManagerDBusProxy.cpp:30:38: error: 'class CommonAPI::DBus::Factory' has no member named 'registerInterface'
12:05:36.093 |      CommonAPI::DBus::Factory::get()->registerInterface(initializeModeManagerDBusProxy);
12:05:36.093 |                                       ^
12:05:36.093 | ../../../git/project/interface/src-gen/v1/com/ivis/MediaManager/PlaybackControlDBusProxy.cpp: In function 'void v1::com::ivis::MediaManager::registerPlaybackControlDBusProxy()':
12:05:36.093 | ../../../git/project/interface/src-gen/v1/com/ivis/MediaManager/PlaybackControlDBusProxy.cpp:30:38: error: 'class CommonAPI::DBus::Factory' has no member named 'registerInterface'
12:05:36.093 |      CommonAPI::DBus::Factory::get()->registerInterface(initializePlaybackControlDBusProxy);
12:05:36.093 |                                       ^
12:05:36.093 | Makefile:478: recipe for target 'release/arm/.obj/ModeManagerDBusProxy.o' failed
12:05:36.093 | make[1] [...]

2017-04-18 17:28 UTC, gunnarx commented
The build errors look like the same as before and it is explained by the 5th comment in this thread.  I will kick off a build based on Morty and report.

2017-04-21 08:22 UTC, gunnarx commented
Initial results for Morty are good or at least consistent with other Morty builds.  I had an unrelated failure on one hardware and still need to rebuild once more before confirming.

2017-04-22 12:00 UTC, gunnarx commented
My builds on Morty were finally confirmed.   Now that morty is finally merged into master I have rebased this PR on latest master and pushed it for you again @summeromance.  Normal PR-checks should now take over.

(Note: because you opened a pull request, GitHub allows pushing updates to that pull request.  And since you opened the PR from your master branch it means I could actually push into *your* master branch.  Kind of scary... hope it's not a problem! :-) )

2017-04-22 12:19 UTC, gunnarx commented
It looks like 9a29db3 was brought in by this PR (it is the hash it has now after rebase) and it seems to be the same purpose as commit 250ee4a2f978 which is already on master.  But they are only almost identical.  

Somewhere during recent merges (morty I guess) it seems we had a merge of README changes because now there is also conflicting information on which layer dependency is the right one.   The Renesas section appears twice.  It's logical if changes were made in different parts of the file that a git-merge might cause both sections to be included.  I tried a quick "git blame" and it shows me a mix of these two commits originally from @slawr, plus strangely enough some line changes that git identifies as coming from @chbae...  I think I'm being fooled a bit here.

Anyway I can't easily figure it out and I don't want to waste time.  Honestly I think the easiest thing is to ignore that for this PR and to make a new commit where the layer dependencies are corrected.  (But as I've said before, I think this info should not be here - we would be much better off referring people to the GDP submodules as the single source of dependency information and not waste time on this.  But that's OK if we have different opinion, just @chbae @slawr I think you disagreed with it last time, so would one of you then use your time to fix the conflicting information now - thanks)

2017-04-24 20:59 UTC, gunnarx commented
Build checks have now executed on the standard master PR checks also.  Porter failure is expected and starter-kit failure is known.  For minnowboard it was successful in my previous build on Morty.  

(finally) +1 from me for merging.

@chbae, for good measure you might want to accept/dismiss your review if you are OK with the changes?

2017-04-25 11:55 UTC, chbae commented
@summeromance Please see my review and others are ok for me.

2017-04-25 11:55 UTC, chbae commented on meta-genivi-dev/recipes-dev-platform/packagegroups/packagegroup-gdp-cdl.bb
> +# Copyright (C) 2015-2016 GENIVI Alliance
# Copyright (C) 2017 GENIVI Alliance

2017-04-26 12:39 UTC, summeromance commented
@chbae Thank you for review. I updated what you reviewed

2017-04-27 06:20 UTC, chbae approved these changes

2017-04-27 09:33 UTC, merged