Added notepad-app recipe
GENIVI/meta-genivi-dev pull request #89
Opened 2017-05-02 15:10 UTC by tahatrue

2017-05-03 02:29 UTC, chbae commented
Please use just one PR for notepad-app. https://github.com/GENIVI/meta-genivi-dev/pull/90 should be integrated in here.

I'll review it tonight. need to change a lot.

Thanks for new application contribution. :)

2017-05-03 02:29 UTC, chbae requested changes
At first, please remove unnecessary comment.

2017-05-03 12:25 UTC, gunnarx commented
> At first, please remove unnecessary comment.

I agree.  Because we are short on time, whoever is merging this can do the fixup.

2017-05-03 13:42 UTC, DunderRoffe commented
I have a cleaned up version on my fork:
https://github.com/dunderroffe/meta-genivi-dev/tree/patch-1

2017-05-03 13:44 UTC, zeenix commented
@DunderRoffe cool, thanks. Can you create a PR?

2017-05-03 15:35 UTC, chbae requested changes
Thanks for integration but need to change somethig.

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +LICENSE = "CLOSED"
Please add "SUMMARY" on top of this bb file.

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +LIC_FILES_CHKSUM = ""
You don't need this line because LICENSE is "CLOSED"

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +SRC_URI = "git://github.com/GENIVI/notepad-app.git;protocol=https \
SRC_URI = "git://github.com/GENIVI/notepad-app.git;protocol=https"

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +RDEPENDS_${PN} = " persistence-client-library "
Why this is RDEPENDS? I thought that it should be persistence-client-library if you are using this.

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +DEPENDS = " qtdeclarative "
DEPENDS = "qtdeclarative"

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    install -d ${D}/usr/share/applications
/usr/share -> ${datadir}

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +                    ${D}/usr/share/applications/com.genivi.gdp.notepad.desktop
/usr/share -> ${datadir}

2017-05-03 15:35 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    /usr/share/* \
/usr/share -> ${datadir}

2017-05-03 16:01 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +RDEPENDS_${PN} = " persistence-client-library "
I checked notepad-app.pro file in your repository. Then you should move persistence-client-library to "DEPENDES"

2017-05-04 08:00 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +# Copyright (C) 2015-2016 GENIVI Alliance
# Copyright (C) 2017 GENIVI Alliance

2017-05-04 09:23 UTC, zeenix commented
@DunderRoffe Can you please squash the fixes to recipe patch? Also a typo: Add recip**t**e summary

2017-05-04 12:07 UTC, chbae commented
To install this application, please add this recipe into packagegroup or image.

2017-05-16 09:49 UTC, gunnarx commented
I got kind of lost in the review feedback.  Anyway, it needed rebase so I now pushed a new version.

2017-05-16 09:56 UTC, gunnarx commented
Build fails, not finding the .desktop file
09:51:43.066 | install: cannot stat '/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0/notepad-app.desktop': No such file or directory

2017-05-16 10:04 UTC, gunnarx commented
Extra files to be installed, are they not normally under a files/ subdirectory?
@DunderRoffe what do you think?  Also, where would you prefer the .desktopfiles - as part of meta-genivi-dev or in the original application repos?

2017-05-16 11:32 UTC, DunderRoffe commented
@gunnarx 
The .desktop files are preferably a part of meta-genivi-dev. They are specific for this platform which mean some apps wont have them in their upstream repo so then we need to put their .desktop files in meta-genivi-dev anyway. Hence, if all apps are handled this way we have a consistent way of doing it for all apps.

2017-05-16 11:32 UTC, DunderRoffe commented
Updated it again. Was missing reference to where to find the .desktop file. Hopefully this works :)

2017-05-16 12:16 UTC, gunnarx commented
Thanks, makes sense to me about the .desktop files.

New build error:
11:35:15.855 ERROR: notepad-app-1.0-r0 do_package_qa: QA Issue: notepad-app: The compile log indicates that host include and/or library paths were used.

Please check the log '/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0/temp/log.do_compile'

2017-05-16 12:18 UTC, gunnarx commented
log.do_compile:

DEBUG: Executing shell function do_compile
NOTE: make -j 8 MAKEFLAGS=-j 8 OE_QMAKE_COMPILER=x86_64-poky-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 OE_QMAKE_CC=x86_64-poky-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 OE_QMAKE_CXX=x86_64-poky-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 OE_QMAKE_CFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0=/usr/src/debug/notepad-app/1.0-r0 -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64=  OE_QMAKE_CXXFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0=/usr/src/debug/notepad-app/1.0-r0 -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64=  -fvisibility-inlines-hidden OE_QMAKE_LINK=x86_64-poky-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 OE_QMAKE_LDFLAGS=-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed OE_QMAKE_AR=x86_64-poky-linux-ar OE_QMAKE_STRIP=echo OE_QMAKE_WAYLAND_SCANNER=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux/usr/bin/wayland-scanner OE_QMAKE_INCDIR_QT=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64//usr/include/qt5
x86_64-poky-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 -c -pipe -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0=/usr/src/debug/notepad-app/1.0-r0 -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64=  -fvisibility-inlines-hidden -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DDLT_2_16 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../git -I. -I/usr/include -I -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/dbus-1.0 -I/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/lib/dbus-1.0/include -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/dlt -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5 -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtQuick -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtGui -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtQml -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtNetwork -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtCore -I. -I/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/lib/qt5/mkspecs/linux-oe-g++ -o main.o ../git/main.cpp
x86_64-poky-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 -c -pipe -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0=/usr/src/debug/notepad-app/1.0-r0 -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64=  -fvisibility-inlines-hidden -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DDLT_2_16 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../git -I. -I/usr/include -I -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/dbus-1.0 -I/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/lib/dbus-1.0/include -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/dlt -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5 -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtQuick -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtGui -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtQml -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtNetwork -isystem /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/include/qt5/QtCore -I. -I/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64/usr/lib/qt5/mkspecs/linux-oe-g++ -o notemanager.o ../git/notemanager.cpp
x86_64-poky-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/qemux86-64 -c -pipe -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/notepad-app/1.0-r0=/usr/src/debug/notepad-app/1.0-r0 -fdebug-prefix-map=/var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/sysroots/x86_64-linux= -fdebug-prefix [...]

2017-05-17 12:06 UTC, DunderRoffe commented
While analyzing this log I found `cc1plus: warning: include location "/usr/include" is unsafe for cross-compilation [-Wpoison-system-directories]`. This warning is because notepad.pro file sets `INCLUDEPATH += /usr/include`. This is not supported while cross-compiling which makes the Quality Assurance in Yocto break the build while packaging .

2017-05-18 10:38 UTC, DunderRoffe commented
While analyzing this log I found `cc1plus: warning: include location "/usr/include" is unsafe for cross-compilation [-Wpoison-system-directories]`. This warning is because notepad.pro file sets `INCLUDEPATH += /usr/include`. This is not supported while cross-compiling which makes the Quality Assurance in Yocto break the build while packaging .

I provided a patch for this locally but it should be upstreamed. However, since I do not have any setup that is able to compile this application outside Yocto I can not verify that this solution would work in the general case.

2017-05-19 08:57 UTC, DunderRoffe commented
@chbae would you have another look? :)

2017-05-19 15:06 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    file://0001-Notepad.pro-Remove-usr-includes-from-include-path.patch \
why don't you contribute this patch to repository?

2017-05-19 15:08 UTC, chbae reviewed
need small change but LGTM.

2017-05-19 15:08 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +DEPENDS = "qtdeclarative persistence-client-library "
DEPENDS = "qtdeclarative persistence-client-library"

2017-05-22 07:08 UTC, DunderRoffe commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    file://0001-Notepad.pro-Remove-usr-includes-from-include-path.patch \
Because I do not know if this patch would work for other solutions than the GDP Yocto build.

2017-05-22 07:09 UTC, DunderRoffe commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +DEPENDS = "qtdeclarative persistence-client-library "
Isn't keeping a space a good practice since it makes it easier to do a "_append"?

2017-05-22 10:34 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +DEPENDS = "qtdeclarative persistence-client-library "
@DunderRoffe 
Basically, all _append should be included space. So this is not good grammar. So I recommend that we can remove ".

2017-05-23 06:59 UTC, chbae commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    file://0001-Notepad.pro-Remove-usr-includes-from-include-path.patch \
Ok. I understand what you are thinking. This is workaround. I agree. Thanks

2017-05-23 06:59 UTC, chbae approved these changes

2017-05-23 12:11 UTC, chbae commented
Tomorrow, I'll test this image and merge soon. If you test yourself, you can merge it. :)

2017-05-24 06:31 UTC, chbae commented
I tested on my raspberrypi3 and it works fine but I can't see application icon in launcher.
@tahatrue Could you add icon?

2017-05-24 06:33 UTC, chbae requested changes
I tested on my raspberrypi3 and it works fine but I can't see application icon in launcher.
@tahatrue Could you add icon?

2017-05-24 07:34 UTC, DunderRoffe commented
@chbae is persisting notes working for you on the RPi3? I tried it on the Minnowboard but did not get PCL to work.

2017-05-24 12:41 UTC, chbae commented
@DunderRoffe
It works on my rpi3 but I can't show icon in launcher as I mentioned. I'll try it on minnowboard tomorrow.

2017-05-24 13:09 UTC, DunderRoffe commented
There is no icon so I made one will set up a PR to the notepad-app repo today.

2017-05-28 23:59 UTC, chbae commented
@DunderRoffe Could you add icon and test again?
In this week, I'll join AGL. So I only can build and review.

2017-05-29 07:09 UTC, DunderRoffe commented
Sorry @chbae never pushed the PR.
Here it is though: https://github.com/GENIVI/notepad-app/pull/2

2017-05-29 14:21 UTC, DunderRoffe commented
The PR is now merged so I updated the recipe accordingly.

2017-05-29 15:04 UTC, gunnarx commented
@DunderRoffe Good that we're running this update through PR checks because it seems to be failing.

2017-05-29 15:09 UTC, gunnarx requested changes

2017-05-29 15:09 UTC, gunnarx commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    install -m 0444 ${S}/notepad.svg
I think you might need a backslash here to prevent the line break from breaking the command.

2017-05-30 07:39 UTC, DunderRoffe commented on meta-genivi-dev/recipes-dev-hmi/genivi-dev-platform-hmi/notepad-app.bb
> +    install -m 0444 ${S}/notepad.svg
Ah yes you are right. I fix

2017-05-30 11:20 UTC, DunderRoffe commented
Added small fix that properly locates the image. This should not effect the builds

2017-05-30 12:23 UTC, DunderRoffe requested changes
Even though the application seems to be working fine with icon etc, something is wrong with the persistence system. Therefore this PR should not be merged until we have verified that the persisting is working as intended

2017-06-07 08:34 UTC, DunderRoffe commented
In order to ease the process of merging meta-genivi-dev into genivi-dev-platform, I close and push this PR to a feature branch "notepadApp". It will be opened again when the reasons for not merging above are resolved.

2017-06-07 08:34 UTC, closed without merging